name: build

on:
  pull_request:
    paths:
      - 'src/**/*.kt'
      - '**.kts'

jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
      - name: Execute tests
        run: |
#          gradle build test
        ./gradlew test
      - name: Install ktlint
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.42.1/ktlint &&
          chmod a+x ktlint &&
          sudo mv ktlint /usr/local/bin/
      - name: Lint with ktlint
        run: |
          ktlint